version: '2'
services: 
  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wp-sinas
    restart: always
    volumes: 
      - ./wp-content:/var/www/html/wp-content
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ~p4sw0rd
    ports:
      - 80:80
      - 443:443
    networks: 
      - back

  db:
    image: mysql:5.7
    container_name: wp-mysql
    restart: always
    volumes: 
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ~p4sw0rd
      MYSQL_DATABASE: atasinas
    networks:
      - back

  phpmyadmin: 
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - 8081:80
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ~p4sw0rd
    networks: 
      - back

networks:
  back:
volumes:
  db_data: